### ISSUE TITLE
Bug and conversion error when specifying `Initial`

### ISSUE THREAD

**Issue by solomonbstoner** [nitram2342/bruteforce-crc#4]
Two issues regarding specifying `initial`. I have already fixed and verified the issue on my computer. Will create a PR soon.

1. When `--initial` is specified, a conversion error is thrown.

![Screenshot from 2021-05-20 15-13-56](https://user-images.githubusercontent.com/24548334/118935523-37e98200-b97e-11eb-9a50-7919464fa717.png)

2. After fixing issue 1, `--probe-initial` should be set to false by default. By setting it to true by default, even when the user specifies `--initial`, the program does not register it and goes ahead with bruteforcing possible initial values.

**Comment by solomonbstoner** [comment]
After applying PR #6 , the program gracefully accepts and uses the CRC seed of 106 given by `--initial 106` 

![Screenshot from 2021-05-20 15-00-40](https://user-images.githubusercontent.com/24548334/118938864-ae3bb380-b981-11eb-8104-c2641190540d.png)

**Comment by nitram2342** [comment]
Thank you very much for fixing this issue!
